name: Update Environment

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'ADE.Sample/**'
  pull_request:
    types: [synchronize]
    paths:
      - 'ADE.Sample/**'

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    name: Setup
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.setup.outputs.name }}
      type: ${{ steps.setup.outputs.type }}
    steps:
      - name: ADE Setup
        id: setup
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: setup

  update:
    name: Update
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    runs-on: ubuntu-latest

    needs: setup
    environment: ${{ needs.setup.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      - name: Build ADE.Sample
        run: dotnet publish ./ADE.Sample -c Release -o ./publish && (cd ./publish && zip -r ../publish.zip .)

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Update Environment
        id: update
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: ensure
          parameters: '{ "name": "${{ needs.setup.outputs.name }}" }'

      - name: Deploy ADE.Sample
        run: |
          az functionapp deployment source config-zip --src publish.zip \
            --subscription $ADE_SUBSCRIPTION --resource-group $ADE_RESOURCE_GROUP --name $ADE_NAME

          echo "- [View environment resources in the Azure portal]($ADE_PORTAL_URL)" >> $GITHUB_STEP_SUMMARY
          echo "- [View the deployed API](https://$ADE_NAME.azurewebsites.net/api/time)" >> $GITHUB_STEP_SUMMARY
