name: Delete Environment

permissions:
  id-token: write

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    name: Setup
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.setup.outputs.type }}
    steps:
      - name: ADE Setup
        id: setup
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: setup

  delete:
    name: Delete
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    needs: setup
    environment: ${{ needs.setup.outputs.type }}

    steps:
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Delete Environment
        id: get
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: delete
